-- Extend invoices for livreur recipients
ALTER TABLE public.invoices
  ADD COLUMN IF NOT EXISTS recipient_type text NOT NULL DEFAULT 'vendeur',
  ADD COLUMN IF NOT EXISTS livreur_id uuid,
  ADD COLUMN IF NOT EXISTS notes text;

ALTER TABLE public.invoices ALTER COLUMN vendeur_id DROP NOT NULL;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'invoices_recipient_consistency') THEN
    ALTER TABLE public.invoices
      ADD CONSTRAINT invoices_recipient_consistency CHECK (
        (recipient_type = 'vendeur' AND vendeur_id IS NOT NULL AND livreur_id IS NULL)
        OR (recipient_type = 'livreur' AND livreur_id IS NOT NULL AND vendeur_id IS NULL)
      );
  END IF;
END $$;

-- Extend invoice items with editable per-order metadata
ALTER TABLE public.invoice_items
  ADD COLUMN IF NOT EXISTS product_name text,
  ADD COLUMN IF NOT EXISTS tracking_number text,
  ADD COLUMN IF NOT EXISTS customer_city text,
  ADD COLUMN IF NOT EXISTS status_snapshot text;

-- Livreurs can view their own invoices
DROP POLICY IF EXISTS "Livreurs see own invoices" ON public.invoices;
CREATE POLICY "Livreurs see own invoices" ON public.invoices
  FOR SELECT TO authenticated USING (livreur_id = auth.uid());

-- Tighten invoice_items visibility (already follows invoices via subquery; no change needed)

-- Invoice schedules table
CREATE TABLE IF NOT EXISTS public.invoice_schedules (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipient_type text NOT NULL UNIQUE CHECK (recipient_type IN ('vendeur','livreur')),
  enabled boolean NOT NULL DEFAULT false,
  frequency_days integer NOT NULL DEFAULT 30 CHECK (frequency_days > 0),
  last_run_at timestamptz,
  next_run_at timestamptz,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by uuid
);

ALTER TABLE public.invoice_schedules ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins manage invoice schedules" ON public.invoice_schedules;
CREATE POLICY "Admins manage invoice schedules" ON public.invoice_schedules
  FOR ALL TO authenticated
  USING (has_role(auth.uid(), 'administrateur'::app_role))
  WITH CHECK (has_role(auth.uid(), 'administrateur'::app_role));

DROP POLICY IF EXISTS "Comptables manage invoice schedules" ON public.invoice_schedules;
CREATE POLICY "Comptables manage invoice schedules" ON public.invoice_schedules
  FOR ALL TO authenticated
  USING (has_role(auth.uid(), 'comptable'::app_role))
  WITH CHECK (has_role(auth.uid(), 'comptable'::app_role));

-- Seed default schedule rows
INSERT INTO public.invoice_schedules (recipient_type, enabled, frequency_days)
VALUES ('vendeur', false, 30), ('livreur', false, 30)
ON CONFLICT (recipient_type) DO NOTHING;

CREATE TRIGGER trg_invoice_schedules_updated
BEFORE UPDATE ON public.invoice_schedules
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();